export const GET_SEARCH_PRODUCTS_REQUEST = "GET_SEARCH_PRODUCTS_REQUEST";
export const GET_SEARCH_PRODUCTS_SUCCESS = "GET_SEARCH_PRODUCTS_SUCCESS";
export const GET_SEARCH_PRODUCTS_FAIL = "GET_SEARCH_PRODUCTS_FAIL";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_BESTSELLER_PRODUCTS_REQUEST =
  "GET_BESTSELLER_PRODUCTS_REQUEST";
export const GET_BESTSELLER_PRODUCTS_SUCCESS =
  "GET_BESTSELLER_PRODUCTS_SUCCESS";
export const GET_BESTSELLER_PRODUCTS_FAIL = "GET_BESTSELLER_PRODUCTS_FAIL";

export const GET_TOPRATED_PRODUCTS_REQUEST = "GET_TOPRATED_PRODUCTS_REQUEST";
export const GET_TOPRATED_PRODUCTS_SUCCESS = "GET_TOPRATED_PRODUCTS_SUCCESS";
export const GET_TOPRATED_PRODUCTS_FAIL = "GET_TOPRATED_PRODUCTS_FAIL";

export const GET_TRENDING_PRODUCTS_REQUEST = "GET_TRENDING_PRODUCTS_REQUEST";
export const GET_TRENDING_PRODUCTS_SUCCESS = "GET_TRENDING_PRODUCTS_SUCCESS";
export const GET_TRENDING_PRODUCTS_FAIL = "GET_TRENDING_PRODUCTS_FAIL";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

//----------------------------------------------------------------
//product reviews
export const ADD_REVIEW_PRODUCT_REQUEST = "ADD_REVIEW_PRODUCT_REQUEST";
export const ADD_REVIEW_PRODUCT_SUCCESS = "ADD_REVIEW_PRODUCT_SUCCESS";
export const ADD_REVIEW_PRODUCT_FAIL = "ADD_REVIEW_PRODUCT_FAIL";

export const DELETE_REVIEW_PRODUCT_REQUEST = "DELETE_REVIEW_PRODUCT_REQUEST";
export const DELETE_REVIEW_PRODUCT_SUCCESS = "DELETE_REVIEW_PRODUCT_SUCCESS";
export const DELETE_REVIEW_PRODUCT_FAIL = "DELETE_REVIEW_PRODUCT_FAIL";
