export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const VERIFIED_REGISTER_USER_REQUEST = "VERIFIED_REGISTER_USER_REQUEST";
export const VERIFIED_REGISTER_USER_SUCCESS = "VERIFIED_REGISTER_USER_SUCCESS";
export const VERIFIED_REGISTER_USER_FAIL = "VERIFIED_REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

//----------------------------------------------------------------

export const GET_WISHLIST_PRODUCTS_REQUEST = "GET_WISHLIST_PRODUCTS_REQUEST";
export const GET_WISHLIST_PRODUCTS_SUCCESS = "GET_WISHLIST_PRODUCTS_SUCCESS";
export const GET_WISHLIST_PRODUCTS_FAIL = "GET_WISHLIST_PRODUCTS_FAIL";

export const GET_CART_PRODUCTS_REQUEST = "GET_CART_PRODUCTS_REQUEST";
export const GET_CART_PRODUCTS_SUCCESS = "GET_CART_PRODUCTS_SUCCESS";
export const GET_CART_PRODUCTS_FAIL = "GET_CART_PRODUCTS_FAIL";

export const ADD_WISHLIST_PRODUCT_REQUEST = "ADD_WISHLIST_PRODUCT_REQUEST";
export const ADD_WISHLIST_PRODUCT_SUCCESS = "ADD_WISHLIST_PRODUCT_SUCCESS";
export const ADD_WISHLIST_PRODUCT_FAIL = "ADD_WISHLIST_PRODUCT_FAILure";

export const REMOVE_WISHLIST_PRODUCT_REQUEST =
  "REMOVE_WISHLIST_PRODUCT_REQUEST";
export const REMOVE_WISHLIST_PRODUCT_SUCCESS =
  "REMOVE_WISHLIST_PRODUCT_SUCCESS";
export const REMOVE_WISHLIST_PRODUCT_FAIL = "REMOVE_WISHLIST_PRODUCT_FAIL";

export const ADD_CART_PRODUCT_REQUEST = "ADD_CART_PRODUCT_REQUEST";
export const ADD_CART_PRODUCT_SUCCESS = "ADD_CART_PRODUCT_SUCCESS";
export const ADD_CART_PRODUCT_FAIL = "ADD_CART_PRODUCT_FAIL";

export const REMOVE_CART_PRODUCT_REQUEST = "REMOVE_CART_PRODUCT_REQUEST";
export const REMOVE_CART_PRODUCT_SUCCESS = "REMOVE_CART_PRODUCT_SUCCESS";
export const REMOVE_CART_PRODUCT_FAIL = "REMOVE_CART_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
